# Generated by Django 4.1.7 on 2023-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Model phone')),
                ('price', models.CharField(max_length=60, verbose_name='Price')),
                ('image', models.FileField(upload_to='', verbose_name='image')),
                ('release_date', models.DateField(verbose_name='Date')),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
        ),
    ]
